# Site settings
title: Your Site Title
description: A description of your site
#baseurl: ""  # Keep this blank if your site is at the root level (e.g., https://example.com)
#url: "https://yourusername.github.io"  # Replace with your site's URL

# Cayman theme settings (Optional, based on the Cayman theme defaults)
theme: jekyll-theme-cayman

# Sass settings for SCSS processing
sass:
    style: compressed          # Choose 'compressed' for minified output or 'expanded' for readable CSS

# Permalink settings (Optional, adjust as needed)
#permalink: pretty  # Example: '/:categories/:title/'

# Markdown settings (Optional, depending on your needs)
markdown: kramdown

# Other settings can be added here as per your project requirements
