theme: "jekyll-theme-cayman"
title: "WordPress Bedrock"
description: "This page showcases the WordPress Bedrock project and outlines its functionality"
navbar:
    - text: "Home"
      url: "/"
    - text: "Example"
      url: "/example"
